In [2]:
import numpy as np

In [3]:
lst = [1, 2, 3]
lst2 = [4, 5, 6]

In [4]:
arr1 = np.array(lst)
arr2 = np.array(lst2)

In [5]:
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [8]:
np.mean(arr1)
# print(np.mean(arr1))

np.float64(2.0)

In [9]:
lst4 = []

for i in range(1001):
    if i % 5 == 0:
        lst4.append(i)

lst4

[0,
 5,
 10,
 15,
 20,
 25,
 30,
 35,
 40,
 45,
 50,
 55,
 60,
 65,
 70,
 75,
 80,
 85,
 90,
 95,
 100,
 105,
 110,
 115,
 120,
 125,
 130,
 135,
 140,
 145,
 150,
 155,
 160,
 165,
 170,
 175,
 180,
 185,
 190,
 195,
 200,
 205,
 210,
 215,
 220,
 225,
 230,
 235,
 240,
 245,
 250,
 255,
 260,
 265,
 270,
 275,
 280,
 285,
 290,
 295,
 300,
 305,
 310,
 315,
 320,
 325,
 330,
 335,
 340,
 345,
 350,
 355,
 360,
 365,
 370,
 375,
 380,
 385,
 390,
 395,
 400,
 405,
 410,
 415,
 420,
 425,
 430,
 435,
 440,
 445,
 450,
 455,
 460,
 465,
 470,
 475,
 480,
 485,
 490,
 495,
 500,
 505,
 510,
 515,
 520,
 525,
 530,
 535,
 540,
 545,
 550,
 555,
 560,
 565,
 570,
 575,
 580,
 585,
 590,
 595,
 600,
 605,
 610,
 615,
 620,
 625,
 630,
 635,
 640,
 645,
 650,
 655,
 660,
 665,
 670,
 675,
 680,
 685,
 690,
 695,
 700,
 705,
 710,
 715,
 720,
 725,
 730,
 735,
 740,
 745,
 750,
 755,
 760,
 765,
 770,
 775,
 780,
 785,
 790,
 795,
 800,
 805,
 810,
 815,
 820,
 825,
 830,
 835,
 840,
 845,
 8

In [22]:
arr4 = np.arange(5, 1001, 5)
np.shape(arr4)
arr4.reshape(25, 8)

array([[   5,   10,   15,   20,   25,   30,   35,   40],
       [  45,   50,   55,   60,   65,   70,   75,   80],
       [  85,   90,   95,  100,  105,  110,  115,  120],
       [ 125,  130,  135,  140,  145,  150,  155,  160],
       [ 165,  170,  175,  180,  185,  190,  195,  200],
       [ 205,  210,  215,  220,  225,  230,  235,  240],
       [ 245,  250,  255,  260,  265,  270,  275,  280],
       [ 285,  290,  295,  300,  305,  310,  315,  320],
       [ 325,  330,  335,  340,  345,  350,  355,  360],
       [ 365,  370,  375,  380,  385,  390,  395,  400],
       [ 405,  410,  415,  420,  425,  430,  435,  440],
       [ 445,  450,  455,  460,  465,  470,  475,  480],
       [ 485,  490,  495,  500,  505,  510,  515,  520],
       [ 525,  530,  535,  540,  545,  550,  555,  560],
       [ 565,  570,  575,  580,  585,  590,  595,  600],
       [ 605,  610,  615,  620,  625,  630,  635,  640],
       [ 645,  650,  655,  660,  665,  670,  675,  680],
       [ 685,  690,  695,  700,

In [25]:
matrix = [[1, 2, 3], [4,  5, 6], [7, 8, 9]]
ar_matrix = np.array(matrix)
print(ar_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
arr5 = np.ones(1000).reshape(125, 8)
arr5

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 